### ISSUE TITLE
undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by burdzz** [bararchy/ruby-SSLscanner#10]
I am having these issues trying to use the scanner. Can you point me in what is going wrong?

```
mburdan$ ruby sslscanner.rb -s google.com -p 443 -c
Scanning, results will be presented by the following colors [strong / weak / vulnerable]

General Checks: 
Generel Settings: Secured Renegotiation
Generel Settings: SSL Compression is disabled

Cipher Checks: 
                Version         Cipher                 Bits        Vulnerability
undefined method `strip' for nil:NilClass
sslscanner.rb:184:in `get_certificate_information'
sslscanner.rb:51:in `ssl_scan'
sslscanner.rb:317:in `block in <main>'
sslscanner.rb:315:in `fork'
sslscanner.rb:315:in `<main>'
```

**Comment by burdzz** [comment]
I found that I was using an older version of ruby on my desktop thinking it was 2.2.0.
