### ISSUE TITLE
Gem is broken (most likly path issues)

### ISSUE THREAD

**Issue by bararchy** [bararchy/ruby-SSLscanner#14]
@wolfedale, is it working for you ? (using the gem )

```
scanssl 
/home/unshadow/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- scanssl/settings (LoadError)
	from /home/unshadow/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/unshadow/.rvm/gems/ruby-2.2.2/gems/scanssl-0.0.1/lib/scanssl.rb:9:in `<top (required)>'
	from /home/unshadow/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/unshadow/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/unshadow/.rvm/gems/ruby-2.2.2/gems/scanssl-0.0.1/bin/scanssl:19:in `<top (required)>'
	from /home/unshadow/.rvm/gems/ruby-2.2.2/bin/scanssl:23:in `load'
	from /home/unshadow/.rvm/gems/ruby-2.2.2/bin/scanssl:23:in `<main>'
	from /home/unshadow/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/unshadow/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wolfedale** [comment]
Yes, you right, there was a problem with including files. I fixed it.
